name: 3dcv-project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.13
  - cython=0.28.5
  - pytorch=1.2.0
  - numpy=1.17.3
  - matplotlib=3.2.1
  - faiss-gpu=1.6.0
  - pillow=8.1.2
  - pip
  - imageio
  - torchvision
  - scikit-image
  - trimesh
  - requests
  - pip:
    - tqdm==4.40.2
    - pyopenvdb